var myString;
var myNum;
var myBool;
var myAny;
var strArr1;
var numArr1;
var boolArr1;
var strArr2;
var numArr2;
var boolArr2;
var strNumTuple;
var myVoid1 = null;
var myVoid2 = undefined;
var myNull = null;
var myUndefined = undefined;
myString = "Hello";
myNum = 22;
myBool = true;
myAny = "5";
strArr1 = ["Hello", "World"];
numArr1 = [1, 2];
boolArr1 = [true, false];
strArr2 = ["Hello", "World"];
numArr2 = [1, 2];
boolArr2 = [true, false];
strNumTuple = ["Hello", 11111];
console.log(myString, myNum, myBool, myAny, strArr1, numArr1, boolArr1, strArr2, numArr2, boolArr2, strNumTuple, myVoid1, myVoid2, myNull, myUndefined);
